import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api, API } from "@/lib/api";
import { ShieldAlert, Loader2 } from "lucide-react";

const verdictStyles = {
  CLEAR: { color: "#1F8A4C", label: "CLEAR — within regional limits" },
  REVIEW: { color: "#B8860B", label: "REVIEW — manual review advised" },
  VIOLATION: { color: "#C0221F", label: "VIOLATION — exceeds regional limits" },
};

export default function VerifyBadge() {
  const { badgeId } = useParams();
  const [record, setRecord] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.get(`/verify/${badgeId}`)
      .then((r) => setRecord(r.data))
      .catch(() => setError("This verification record does not exist or has been removed."));
  }, [badgeId]);

  if (error) {
    return (
      <div className="mx-auto max-w-lg px-6 py-24 text-center" data-testid="verify-badge-page">
        <ShieldAlert className="mx-auto h-10 w-10 text-red-400" />
        <h1 className="mt-6 font-display text-3xl text-[#F0E9D6]">Not found</h1>
        <p className="mt-3 text-[#F0E9D6]/65" data-testid="verify-badge-error">{error}</p>
      </div>
    );
  }
  if (!record) {
    return (
      <div className="mx-auto max-w-lg px-6 py-24 text-center">
        <Loader2 className="mx-auto h-8 w-8 animate-spin text-[#0047FF]" />
      </div>
    );
  }

  const V = verdictStyles[record.verdict] || verdictStyles.REVIEW;

  return (
    <div className="mx-auto max-w-2xl px-6 py-16" data-testid="verify-badge-page">
      <div className="rounded-md border border-[#D4FF00]/30 bg-[#24242C] p-10">
        <div className="flex items-center gap-3">
          <img src="/brand/logo-icon.png" alt="SonicCheck" className="h-12 w-12 object-contain" />
          <div>
            <div className="text-[10px] uppercase tracking-widest text-[#F0E9D6]/50 font-mono-data">Public verification record</div>
            <div className="font-display text-xl text-[#F0E9D6]">Verified by SonicCheck</div>
          </div>
        </div>

        <div className="mt-8">
          <div className="text-[10px] uppercase tracking-widest text-[#F0E9D6]/50 font-mono-data">Work</div>
          <h1 data-testid="verify-badge-title" className="font-display text-4xl text-[#F0E9D6] mt-1">{record.title}</h1>
          <div className="mt-1 text-[#F0E9D6]/65">{record.artist_name || "—"}</div>
        </div>

        <div className="mt-8 grid gap-3 sm:grid-cols-2">
          <div className="rounded-md border border-white/10 bg-[#1C1C22] p-4">
            <div className="text-[10px] uppercase tracking-widest text-[#F0E9D6]/50 font-mono-data">Similarity score</div>
            <div data-testid="verify-badge-score" className="mt-1 font-mono-data text-4xl text-[#F0E9D6]">{record.overall_score}<span className="text-lg text-[#F0E9D6]/50">%</span></div>
          </div>
          <div className="rounded-md border border-white/10 bg-[#1C1C22] p-4">
            <div className="text-[10px] uppercase tracking-widest text-[#F0E9D6]/50 font-mono-data">Verdict</div>
            <div data-testid="verify-badge-verdict" className="mt-2 inline-flex rounded-full border px-3 py-1 text-xs font-mono-data uppercase tracking-widest" style={{ color: V.color, borderColor: `${V.color}66`, background: `${V.color}1a` }}>
              {record.verdict}
            </div>
            <div className="mt-2 text-xs text-[#F0E9D6]/50">{V.label}</div>
          </div>
        </div>

        <div className="mt-4 rounded-md border border-white/10 bg-[#1C1C22] p-4 text-sm text-[#F0E9D6]/85">
          <div className="grid gap-1 font-mono-data text-xs">
            <div><span className="text-[#F0E9D6]/50">Jurisdiction:</span> {record.region_name} ({record.region}) · {record.doctrine}</div>
            <div><span className="text-[#F0E9D6]/50">Checks:</span> {record.scan_modes?.audio ? "Audio fingerprint" : null}{record.scan_modes?.audio && record.scan_modes?.lyrics ? " + " : ""}{record.scan_modes?.lyrics ? "AI lyric analysis" : null}</div>
            <div><span className="text-[#F0E9D6]/50">Scanned:</span> {record.scanned_at?.slice(0, 10)}</div>
            <div><span className="text-[#F0E9D6]/50">Record ID:</span> {record.badge_id}</div>
          </div>
        </div>

        <div className="mt-6 flex justify-center">
          <img src={`${API}/verify/${badgeId}/badge.svg`} alt="Verified by SonicCheck badge" data-testid="verify-badge-svg" />
        </div>

        <p className="mt-6 text-center text-xs text-[#F0E9D6]/40">
          This record was generated by SonicCheck's automated plagiarism analysis. It is not legal advice.
        </p>
      </div>

      <div className="mt-8 text-center">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-[#F0E9D6]/65 hover:text-[#F0E9D6]">
          <img src="/brand/logo-icon.png" alt="" className="h-5 w-5 object-contain" /> Check your own music at SonicCheck
        </Link>
      </div>
    </div>
  );
}
